const data = {
  products: [
    {
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/assets/shirt2.jpg",
      price: 40,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "M&D Fit Shirt",
      slug: "m&d-fit-shirt",
      category: "Shirts",
      image: "/assets/shirt3.jpg",
      price: 25,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Nike Slim Trousers",
      slug: "nike-slim-trousers",
      category: "Pants",
      image: "/assets/trousers1.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Trousers",
      slug: "adidas-fit-pant",
      category: "Trousers",
      image: "/assets/trousers2.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    }
  ],
};
export default data;
